---

service: designguideme-serverless # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: rust
  region: eu-central-1
  stage: v1

plugins:
  - serverless-rust
  - serverless-domain-manager

package:
  individually: true

functions:
  test:
    handler: messages
    events:
      - http:
          path: /messages
          method: POST

custom:
  customDomain:
    domainName: api.designguide.me
    basePath: ${self:provider.stage}
    createRoute53Record: true


