---

service: designguideme-serverless # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: rust
  region: eu-central-1
  stage: dev

plugins:
  - serverless-rust
  - serverless-domain-manager

package:
  individually: true

functions:
  messages:
    handler: messages
    events:
      - http:
          path: /messages
          method: POST

custom:
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: v1

  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.designguide.me
    dev: dev-api.designguide.me
