[package]
name = "json_converter"
version = "0.1.0"
authors = ["Patrick Kissling <patrick.kissling@gmx.de>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.2.*"
serde = "1.0.*"
serde_json = "1.0.*"